Initial pull request
wolox-training/ee-react-native pull request #1
Opened 2018-11-27 16:30 UTC by EmmanuelWLX

## Summary 
- Initial kickoff
- Added tittle
- Tech component

2018-11-27 21:30 UTC, FrankIglesias requested changes

2018-11-27 21:30 UTC, FrankIglesias commented on scss/application.scss
> +@import 'tech';
at tailing empty line at the end of the file

2018-11-27 21:30 UTC, FrankIglesias commented on scss/styles.scss
> +$text-small: 12px;
same

2018-11-27 21:30 UTC, FrankIglesias commented on scss/tech.scss
> +  .release,
check indentation (1 tab = 2 spaces)

2018-11-27 21:30 UTC, FrankIglesias commented on scss/tech.scss
> +  	top: 10px;
remve this

2018-11-27 21:30 UTC, FrankIglesias commented on scss/tech.scss
> +}
same

2018-11-27 21:30 UTC, FrankIglesias commented on scss/tech.scss
> +
remove empty line

2018-11-27 21:30 UTC, FrankIglesias commented on scss/tech.scss
> +    position: absolute;
remove this

2018-11-27 21:30 UTC, FrankIglesias commented on scss/tech.scss
> +    top: 15px;
and this

2018-11-27 21:30 UTC, FrankIglesias commented on scss/tech.scss
> +  &::after {
check indentation

2018-11-27 21:30 UTC, FrankIglesias commented on scss/titles.scss
> +  padding: 50px 0 0 50px;
this can be center aligned

2018-11-27 21:30 UTC, FrankIglesias commented on scss/titles.scss
> +}
same

2018-11-28 14:27 UTC, EmmanuelWLX commented on scss/tech.scss
> +  	top: 10px;
the whole class or only the top property?

2018-11-28 14:30 UTC, EmmanuelWLX commented on scss/tech.scss
> +    position: absolute;
the whole class? :(

2018-12-02 14:00 UTC, FrankIglesias requested changes

2018-12-02 14:00 UTC, FrankIglesias commented on index.html
> +  <div>
this div can be deleted

2018-12-02 14:00 UTC, FrankIglesias commented on index.html
> +      <h1 class="nombre">ReactJS</h1>
use a less important tag for tech names

2018-12-02 14:00 UTC, FrankIglesias commented on index.html
> +      <img src="assets/react_icon.svg" class="tech-logo"/>
add alt to all images

2018-12-02 14:00 UTC, FrankIglesias commented on index.html
> +</html>
add tailing empty line

2018-12-02 14:00 UTC, FrankIglesias commented on scss/application.scss
> +@import 'tech';
add tailing empty line

2018-12-02 14:00 UTC, FrankIglesias commented on scss/colors.scss
> +$grey: #C4C4C4;
add tailing empty line

2018-12-02 14:00 UTC, FrankIglesias commented on scss/tech.scss
> +
remove empty line

2018-12-03 14:24 UTC, closed without merging