Added profile page
wolox-training/ee-react-native pull request #13
Opened 2019-01-30 20:46 UTC by EmmanuelWLX

### Summary
- Added profile page

### Screenshots
![profile](https://user-images.githubusercontent.com/45210177/52011477-dbb17a00-24b6-11e9-85f5-fa99f34b86bb.png)

### Trello card
https://trello.com/c/NYwZYErf/7-react-app-ii-other-views

2019-01-31 05:01 UTC, julibel requested changes

2019-01-31 05:01 UTC, julibel commented on React/tic-tac-toe/src/app/screens/Game/constants.js
> +/* eslint-disable no-magic-numbers */
why is this here?

2019-01-31 05:01 UTC, julibel commented on React/tic-tac-toe/src/app/screens/Game/index.js
> +        // eslint-disable-next-line react/no-array-index-key
mmmm you can do better

2019-01-31 05:01 UTC, julibel commented on React/tic-tac-toe/src/app/screens/Profile/index.js
> +              <li className="match-img-1" />
use a map and a list instead of this..

2019-01-31 05:01 UTC, julibel commented on React/tic-tac-toe/src/app/screens/Profile/index.js
> +              <li className="match-1">Match #359</li>
same

2019-01-31 05:01 UTC, julibel commented on React/tic-tac-toe/src/app/screens/Profile/index.js
> +
delete empty line

2019-01-31 13:33 UTC, EmmanuelWLX commented on React/tic-tac-toe/src/app/screens/Game/constants.js
> +/* eslint-disable no-magic-numbers */
i extracted the rows as constants, and i thought that was unnecessary to extract the cell numbers too... but i can fix it if it is necessary

2019-01-31 14:30 UTC, EmmanuelWLX commented on React/tic-tac-toe/src/app/screens/Game/constants.js
> +/* eslint-disable no-magic-numbers */
i removed that eslint disable and i got no problems from linter... i think i did a bad rollback of frank's changes, and the problem is that i hadn't committed the changes :cry:

2019-02-01 00:14 UTC, julibel commented on React/tic-tac-toe/src/app/screens/Game/constants.js
> +/* eslint-disable no-magic-numbers */
it's ok! leave it like this

2019-02-01 00:16 UTC, julibel approved these changes

2019-02-06 19:13 UTC, merged